### ISSUE TITLE
already minted txid are creating an alert

### ISSUE THREAD

**Issue by eckelj** [rddl-network/rddl-2-plmnt-service#73]
ip-10-22-26-19.eu-north-1.compute.internal <no-reply@rddl.io>
7:02 AM (1 hour ago)
to alert

Sep 30 04:03:05 ip-10-22-26-19 rddl-2-plmnt[350970]: ts=2024-09-30T04:03:05.958573492Z caller=level.go:71 level=info msg="error while fetching mint request: txid c62c1a453c4b017cdbeaf28b9f86e62006cb5442a609a5d08a18509a7d439dad got minted before (mintRequest:<beneficiary:\"plmnt1p498zlxe4yhz5wqllgvk22ucnezgje5f9zexwz\" amount:1094946 liquidTxHash:\"c62c1a453c4b017cdbeaf28b9f86e62006cb5442a609a5d08a18509a7d439dad\" > )"

**Comment by GR3G0RYO** [comment]
Needs to be released to the Testnet check if it works

**Comment by eckelj** [comment]
got fixed in the meantime
